### PR TITLE
CooRnet Graphical User Interface 

### PR DESCRIPTION
**Pull request by GiacomoDiFa**
I made the CooRnet graphical interface.
I did some tests with the input validations, but I have a few url files to process.
Can you let your colleagues try it?
I remind you that this version takes only the head of the data frame containing the URLs as input.
For the full version just remove the head function in get_ctshares

### CODE REVIEW

**Comment by fabiogiglietto** [comment]
Can you remove the head limit in the code to allow proper tests with the full list of URL?

**Comment by GiacomoDiFa** [comment]
I do it. During the test check also the R terminal for seeing if api request works.

**Comment by fabiogiglietto** [comment]
```
library("devtools")
devtools::install_github("GiacomoDiFa/CooRnet")
```

fails with

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘shinyjs’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```
please make sure that the forked package actually installs to allow proper testing.

**Comment by GiacomoDiFa** [comment]
Try again! :)

**Comment by fabiogiglietto** [comment]
```
> library(CooRnet)
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 
Warning message:
replacing previous import ‘shiny::runExample’ by ‘shinyjs::runExample’ when loading ‘CooRnet’ 
> CooRnet::gui()
Loading required package: shiny
Failed with error:  ‘Package ‘shiny’ version 1.7.2 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘shiny’ is imported by ‘miniUI’, ‘CooRnet’ so cannot be unloaded
```

I got these weird warnings when loading the package and launching the gui.

**Pull request closed without merging**
